email_to: "connect@howellmarine.co.uk"

sites:
  - "https://projects.worldbank.org/en/projects-operations/projects-list?cons_serv_reqd_ind_exact=Yes&os=0&status_exact=Active&qterm=marine"
  - "https://wbgeprocure-rfxnow.worldbank.org/rfxnow/public/advertisement/index.html;jsessionid=CDA39310013F409DEB0B8D2326EF03D3"
  - "https://www.sell2wales.gov.wales/search/search_mainpage.aspx?results=true"
  - "https://www.publiccontractsscotland.gov.uk/search/search_mainpage.aspx"
  - "https://procontract.due-north.com/Opportunities/"
  - "https://iucn.org/procurement/currently-running-tenders"
  - "https://www.oecs.org/en/work-with-us/procurements/current-tenders"
  - "https://beo-procurement.iadb.org/home"
  - "https://www.ioc.unesco.org/en/professional-opportunities"
  - "https://selfservice.adb.org/OA_HTML/adb/adbpos/jsp/ADBCMSHomepage.jsp"
  - "https://www.afdb.org/en/projects-and-operations/procurement"
  - "https://www.ungm.org/Public/Notice"
  - "https://thecommonwealth.org/procurement"
  - "https://inspira.un.org/psp/PUNA1J/?cmd=login&languageCd=ENG"
  - "https://jobs.undp.org/cj_view_consultancies.cfm"
  - "https://www.unep.org/calls-for-proposals"
  - "https://careers.un.org/"
  - "https://www.etenders.gov.ie/epps/viewCFTSAction.do"
  - "https://www.conservation.org/about/procurement-opportunities"
  - "https://www.ospar.org/organisation/calls-to-tender"
  - "https://reliefweb.int/jobs?search=marine"
  - "https://nexxe.gep.com/weforum/anonymous#/rfx_workbench_public/weforum"
  - "https://in-tendhost.co.uk/gggi/aspx/Tenders/Current"
  - "https://www.contractsfinder.service.gov.uk/Search"
  - "https://www.find-tender.service.gov.uk/Search/Results"
  - "https://crfm.int/~uwohxjxf/index.php?option=com_k2&view=itemlist&task=category&id=114:jobs-and-consultancies&Itemid=303"
  - "https://ted.europa.eu/en/search/result?FT=blue+economy&search-scope=ACTIVE"
  - "https://caricom.org/procurement-notices/"
  - "https://e-sourcingni.bravosolution.co.uk/web/login.shtml"
  - "https://mibema.go.ke/tender-notices"
  - "https://medblueconomyplatform.org/vkc/news/"
  - "https://www.ntb.sc/tenders"
  - "https://kemfsed.org/tenders/"
  - "https://www.ukri.org/opportunity"
  - "https://esmeefairbairn.org.uk/latest-news"
  - "https://www.caribank.org/work-with-us/procurement/procurement-notices"
  - "https://www.norad.no/en/for-partners/guides-and-tools/calls-for-proposals2/"
  - "https://www.wri.org/about/procurement-opportunities"
  - "https://www.worldwildlife.org/pages/wwf-gef-vacancies"
  - "https://asean.org/recent-procurement"
  - "https://blueventures.org/about/careers/"
  - "https://www.procurement.gd/contract-notices"
  - "https://www.govt.lc/tenders"
  - "https://www.gov.bb/Government/tenders"
  - "https://www.ttconnect.gov.tt/index.php/tender-notices/"
  - "https://bvi.gov.vg/tags/tender-notices"
  - "https://dominica.gov.dm/notices"
  - "https://www.mercator-ocean.eu/about-us/work-with-us/calls-for-tender/"
